language: node_js
node_js:
    - "4"
    - "5"
    - "6"
    - "7"
sudo: false
script: "npm test && npm run docs"
after_success:
    - npm run coveralls
addons:
    code_climate:
        repo_token: 05997825896298d07ba270005ef2ceaf987b95ceff15e59286788b5a2a91852c
